### PR TITLE
label form designer

### LINKED ISSUE #1213: Form Designer: switch button to show Labels/Names of attributes
Now Form Designer view we can only see attributes' labels. If we will have to fix a survey from Mongolia, containing only Mongolian text (for labels), we cannot work with that because we do not understand the content. We need to be able to see attributes' names, alternatively. 

For example is Collect we only see Names, and this works very well (even with surveys coming from Vietnam, Cambodia etc).

### PR DESCRIPTION
**Pull request by ramirobg94**
resolves #1213

### CODE REVIEW

**Review by SteRiccio — DISMISSED** [review]

File: webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ const ColumnHeader = (props) => {
   })
 
   const nodeDefUuid = NodeDef.getUuid(nodeDef)
-  const nodeDefLabel = NodeDef.getLabel(nodeDef, lang)
+  const nodeDefLabel = itemLabelFunction(nodeDef, lang)
```
Comment (minotogna) [inline webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js:47]: dont we have a hook to get node def label?

Comment (ramirobg94) [reply webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js:47]: We have a selector into store/survey/state which is getNodeDefLabel

`
export const getNodeDefLabel = (nodeDef) => (state) => {
  const surveyInfo = getSurveyInfo(state)
  const langApp = I18nState.getLang(state)
  const langSurvey = Survey.getLanguage(langApp)(surveyInfo)
  return NodeDef.getLabel(nodeDef, langSurvey)
}
`

so maybe we should add a property to redux -> webapp/store/ui/ and store there the label function selected by the user and avoid to propagate through all of the components.

What do you think?

Comment (minotogna) [reply webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js:47]: I dont think we need to store in redux the function. we can just add a hook `webapp/store/survey/hooks/index.js` useNodeDefLabel(nodeDef)=>{...} that calls the state selector

Comment (ramirobg94) [reply webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js:47]: how do we change the function to use into the useNodeDefLabel, the local State, or the global State?

I mean now we have a switch on the UI which uses a hook which is useLabelFunctionSelector, but at the end, we need to propagate this ItemLabelFunction or store in some global Storage to share between components without the need to propagate

Comment (SteRiccio) [reply webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js:47]: I think that Ramiro talks about a place where we can store the preference about the preferred way to show the node defs, by name or by label, so Redux store looks like the perfect place for this (and maybe in the store we can "store" only the code of the selected option, not the function).

Comment (minotogna) [reply webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js:47]: I'm talking about the function @SteRiccio

File: webapp/components/survey/ItemLabelFunctionSelector/ItemLabelFunctionSelector.js [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+  const toggleLabelFunction = () => {
+    dispatch(SurveyFormActions.toggleNodeDefLabelFunction())
+  }
+
+  return (
+    <ButtonGroup
+      selectedItemKey={nodeDefLabelFunction === NodeDef.getName ? labelTypesKeys.byName : labelTypesKeys.byLabel}
+      onChange={toggleLabelFunction}
+      items={labelTypes({ i18n })}
+    />
```
Comment (minotogna) [inline webapp/components/survey/ItemLabelFunctionSelector/ItemLabelFunctionSelector.js:39]: as discussed, we can show only one button

File: webapp/components/survey/ItemLabelFunctionSelector/ItemLabelFunctionSelector.js [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+]
+
+const ItemLabelFunctionSelector = () => {
+  const i18n = useI18n()
+  const dispatch = useDispatch()
+
+  const nodeDefLabelFunction = useSelector(SurveyFormState.nodeDefLabelFunction)
+
+  const toggleLabelFunction = () => {
+    dispatch(SurveyFormActions.toggleNodeDefLabelFunction())
```
Comment (minotogna) [inline webapp/components/survey/ItemLabelFunctionSelector/ItemLabelFunctionSelector.js:31]: this is a generic component, it can be used also in hierarch. pass the onChange function to this component

File: webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.js [hunk 4]
```diff
@@ -17,13 +19,13 @@ const AttributeSelector = (props) => {
...
     onToggleAttribute,
     showMultipleAttributes,
-    itemLabelFunction,
   } = props
   const isAttributeFn = showMultipleAttributes ? NodeDef.isAttribute : NodeDef.isSingleAttribute
   const isVisible =
     (isAttributeFn(nodeDef) || NodeDef.isEqual(nodeDef)(nodeDefContext)) &&
     (R.isEmpty(filterTypes) || R.includes(NodeDef.getType(nodeDef), filterTypes))
 
+  const itemLabelFunction = useSelector(SurveyFormState.getNodeDefLabel)
```
Comment (minotogna) [inline webapp/components/survey/NodeDefsSelector/AttributesSelector/AttributeSelector.js:28]: this is a generic component. it has nothing to do with form

File: webapp/components/survey/NodeDefsSelector/EntitySelector/EntitySelector.js [hunk 5]
```diff
@@ -26,8 +29,9 @@ const getDropdownItems = (hierarchy, lang, itemLabelFunction) => {
 }
 
 const EntitySelector = (props) => {
-  const { hierarchy, nodeDefUuidEntity, lang, validation, onChange, itemLabelFunction } = props
+  const { hierarchy, nodeDefUuidEntity, lang, validation, onChange } = props
 
+  const itemLabelFunction = useSelector(SurveyFormState.getNodeDefLabel)
```
Comment (minotogna) [inline webapp/components/survey/NodeDefsSelector/EntitySelector/EntitySelector.js:34]: this is a generic component. it has nothing to do with form

File: webapp/store/ui/record/reducer.js [hunk 6]
```diff
@@ -3,7 +3,7 @@ import { exportReducer } from '@webapp/utils/reduxUtils'
 import { SystemActions } from '@webapp/store/system'
 
 import { SurveyActions } from '@webapp/store/survey'
-import { SurveyFormActions } from '@webapp/store/ui/surveyForm'
+import * as SurveyFormActions from '../surveyForm/actions'
```
Comment (minotogna) [inline webapp/store/ui/record/reducer.js:6]: this must be as it was before

File: webapp/store/ui/surveyForm/actions.js [hunk 7]
```diff
@@ -44,14 +44,25 @@ export const toggleFormPageNavigation = () => (dispatch, getState) => {
...
 export const formExpandedPageNavigationUpdate = 'survey/form/expandedPageNavigation/update'
 
 export const toggleExpandedFormPageNavigation = () => (dispatch, getState) => {
   const expandedPageNavigation = !SurveyFormState.expandedPageNavigation(getState())
   dispatch({ type: formExpandedPageNavigationUpdate, expandedPageNavigation })
 }
 
+// toggle form nodeDef label function
+export const formToggleNodeDefLabelFunction = 'survey/form/toggleNodeDefLabelFunction/update'
+export const toggleNodeDefLabelFunction = () => (dispatch, getState) => {
```
Comment (minotogna) [inline webapp/store/ui/surveyForm/actions.js:57]: can this be called updateNodeDefDisplayType?

File: webapp/store/ui/surveyForm/actions.js [hunk 8]
```diff
@@ -44,14 +44,25 @@ export const toggleFormPageNavigation = () => (dispatch, getState) => {
...
+// Toggle form page navigation expanded
 export const formExpandedPageNavigationUpdate = 'survey/form/expandedPageNavigation/update'
 
 export const toggleExpandedFormPageNavigation = () => (dispatch, getState) => {
   const expandedPageNavigation = !SurveyFormState.expandedPageNavigation(getState())
   dispatch({ type: formExpandedPageNavigationUpdate, expandedPageNavigation })
 }
 
+// toggle form nodeDef label function
+export const formToggleNodeDefLabelFunction = 'survey/form/toggleNodeDefLabelFunction/update'
```
Comment (minotogna) [inline webapp/store/ui/surveyForm/actions.js:56]: can this be called formNodeDefDisplayTypeUpdate?

File: webapp/store/ui/surveyForm/actions.js [hunk 9]
```diff
@@ -44,14 +44,25 @@ export const toggleFormPageNavigation = () => (dispatch, getState) => {
...
+export const toggleNodeDefLabelFunction = () => (dispatch, getState) => {
+  const nodeDefLabelFunction = SurveyFormState.nodeDefLabelFunction(getState())
+
+  dispatch({
+    type: formToggleNodeDefLabelFunction,
+    nodeDefLabelFunction: nodeDefLabelFunction === NodeDef.getLabel ? 'getName' : 'getLabel',
```
Comment (minotogna) [inline webapp/store/ui/surveyForm/actions.js:62]: properties are either name or label

File: webapp/store/ui/surveyForm/state.js [hunk 10]
```diff
@@ -92,6 +95,19 @@ export const expandedPageNavigation = getStateProp(keys.expandedPageNavigation,
 
 export const setExpandedPageNavigation = (value) => R.assoc(keys.expandedPageNavigation, value)
 
+// ============ Form nodeDef label Function
+export const nodeDefLabelFunction = getStateProp(keys.nodeDefLabelFunction, NodeDef.getLabel)
```
Comment (minotogna) [inline webapp/store/ui/surveyForm/state.js:99]: this should be getNodeDefDisplayType

File: webapp/store/ui/surveyForm/state.js [hunk 11]
```diff
@@ -19,6 +21,7 @@ const keys = {
   nodeDefUuidPageNodeUuid: 'nodeDefUuidPageNodeUuid', // Map of nodeDefUuid -> nodeUuid representing the node loaded in page nodeDefUuid
   showPageNavigation: 'showPageNavigation',
   expandedPageNavigation: 'expandedPageNavigation',
+  nodeDefLabelFunction: 'nodeDefLabelFunction', // NodeDef label function
```
Comment (minotogna) [inline webapp/store/ui/surveyForm/state.js:24]: nodeDefDisplayType

File: webapp/store/ui/surveyForm/state.js [hunk 12]
```diff
@@ -92,6 +95,19 @@ export const expandedPageNavigation = getStateProp(keys.expandedPageNavigation,
 
 export const setExpandedPageNavigation = (value) => R.assoc(keys.expandedPageNavigation, value)
 
+// ============ Form nodeDef label Function
+export const nodeDefLabelFunction = getStateProp(keys.nodeDefLabelFunction, NodeDef.getLabel)
+
+export const setNodeDefLabelFunction = (value) => R.assoc(keys.nodeDefLabelFunction, NodeDef[value])
```
Comment (minotogna) [inline webapp/store/ui/surveyForm/state.js:101]: as above

File: webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js [hunk 13]
```diff
@@ -1,21 +1,24 @@
...
-import { useLabelFunctionSelector } from '@webapp/components/hooks'
 import { NodeDefsSelector } from '@webapp/components/survey/NodeDefsSelector'
+import ItemLabelFunctionSelector from '@webapp/components/survey/ItemLabelFunctionSelector'
 
 import Tree from './Tree'
 
 const SurveyHierarchy = () => {
   const i18n = useI18n()
   const survey = useSurvey()
+  const itemLabelFunction = useSelector(SurveyFormState.getNodeDefLabel)
```
Comment (minotogna) [inline webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js:21]: this should be its own. this is not a global change

**Review by minotogna — CHANGES_REQUESTED** [review]

File: webapp/store/ui/surveyForm/actions.js [hunk 14]
```diff
@@ -44,14 +44,25 @@ export const toggleFormPageNavigation = () => (dispatch, getState) => {
...
 }
 
+// toggle form nodeDef label function
+export const formUpdateNodeDefDisplayType = 'survey/form/updateNodeDefDisplayType/update'
+export const updateNodeDefDisplayType = () => (dispatch, getState) => {
+  const nodeDefDisplayType = SurveyFormState.getNodeDefDisplayType(getState())
+
+  dispatch({
+    type: formUpdateNodeDefDisplayType,
+    nodeDefDisplayType: nodeDefDisplayType === NodeDef.getLabel ? NodeDef.getName : NodeDef.getLabel,
```
Comment (minotogna) [inline webapp/store/ui/surveyForm/actions.js:62]: this should either label or name. it's not a function

File: webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js [hunk 15]
```diff
@@ -22,9 +22,9 @@ const SurveyHierarchy = () => {
 
   const [selectedNodeDefUuid, setSelectedNodeDefUuid] = useState(null)
   const [tree, setTree] = useState(null)
+  const [[nodeDefDisplayType], setNodeDefDisplayType] = useState([NodeDef.getLabel])
```
Comment (minotogna) [inline webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js:25]: this is not a function.
From the displayType component you can export 
```
DisplayType = {
label:'label',
name:'name'
}
```

File: webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js [hunk 16]
```diff
@@ -27,6 +29,7 @@ const ColumnHeader = (props) => {
 
   const i18n = useI18n()
   const lang = useSurveyLang()
+  const getNodeDefDisplayLabel = useSelector(SurveyFormState.getNodeDefDisplayLabel)
```
Comment (minotogna) [inline webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnHeader.js:32]: you cannot use SurveyFormState in DataQuery. add this prop to DataQuery state as well

**Review by minotogna — CHANGES_REQUESTED** [review]

File: webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js [hunk 17]
```diff
@@ -53,11 +61,11 @@ const SurveyHierarchy = () => {
...
           canSelectAttributes={false}
           showAncestors={false}
-          itemLabelFunction={itemLabelFunction}
+          nodeDefLabelType={nodeDefLabelType}
         />
       </div>
       <div className="survey-hierarchy__label-selector">
-        <ItemLabelFunctionSelector />
+        <NodeDefLabelSwitch labelType={nodeDefLabelType} onChange={toggleLabelFunction} />
       </div>
```
Comment (minotogna) [inline webapp/views/App/views/Designer/SurveyHierarchy/SurveyHierarchy.js:69]: can this be moved on top left of the page?

**Review by minotogna — APPROVED** [review]
