### PR TITLE
Fixed NodeDefEditCode displayAs update

### LINKED ISSUE #676: NodeDefEdit Code: display as update
- [x] Changing DisplayAs from checkbox to dropdown list,  code gets displayed as page and disappears from parent page

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #676

### CODE REVIEW

File: webapp/survey/nodeDefs/actions.js [hunk 1]
```diff
@@ -14,12 +14,12 @@ import { appModuleUri, designerModules } from '@webapp/app/appModules'
 
 import * as AppState from '@webapp/app/appState'
 import * as NotificationState from '@webapp/app/appNotification/appNotificationState'
-import * as SurveyState from '../surveyState'
 import * as NodeDefState from '@webapp/loggedin/surveyViews/nodeDef/nodeDefState'
```
Comment (minotogna) [inline webapp/survey/nodeDefs/actions.js:17]: use relative imports here as well

Comment (SteRiccio) [reply webapp/survey/nodeDefs/actions.js:17]: ok
