### PR TITLE
DataVis: fixed error fetching data from virtual entity (uuid column not found)

### LINKED ISSUE #834: DataVis: error fetching data from virtual entity (column virtualEntityName_uuid does not exist)

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixed #834

### CODE REVIEW

File: common/model/db/views/dataNodeDef/view.js [hunk 1]
```diff
@@ -44,12 +44,14 @@ export default class ViewDataNodeDef extends TableDataNodeDef {
...
+  get columnNodeDefUuid() {
+    // node def can be the entity itself or it's source entity (if virtual)
+    const { nodeDef } = this.tableData
+    return new ColumnNodeDef(this, nodeDef)
   }
 
-  get columnNodeDefUuid() {
-    return new ColumnNodeDef(this, this.nodeDef)
+  get columnUuid() {
+    return this.columnNodeDefUuid.namesFull[0]
```
Comment (minotogna) [inline common/model/db/views/dataNodeDef/view.js:54]: I would add a method to column nameFull. what do u think?

Comment (SteRiccio) [reply common/model/db/views/dataNodeDef/view.js:54]: ok
