### PR TITLE
Fixed DataVis edit mode - calculated attributes read only

### LINKED ISSUE #725: DataVis: Edit mode calculated attributes
In DataVis edit mode, calculated attribute values are not shown.

- [x] Show attribute values in read only mode and with background color as table selector header (see mockup of first row in attachment)

Screen Shot 2020-04-19 at 11 29 59

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixed #725

### CODE REVIEW

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js [hunk 1]
```diff
@@ -1,77 +1,76 @@
...
+        parentNode={parentNode}
+        nodes={[node]}
+        entry
+        entryDataQuery
+        edit={false}
+        renderType={NodeDefLayout.renderType.tableBody}
+        canEditRecord={canEditRecord}
+        updateNode={updateNode}
+        removeNode={removeNode}
+        createNodePlaceholder={createNodePlaceholder}
```
Comment (minotogna) [inline webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:49]: can we avoid passing the actions here and use them directly where it's needed with dispatch(action)?

File: server/modules/surveyRdb/manager/surveyRdbManager.js [hunk 2]
```diff
@@ -100,22 +102,35 @@ export const queryTable = async (
...
+              })
+            )
+          } else if (NodeDef.isMultiple(nodeDefTable) && NodeDef.isEqual(nodeDefCol)(nodeDefTable)) {
+            // Column is the multiple attribute
+            node = await NodeRepository.fetchNodeByUuid(surveyId, row[RdbDataView.getColUuid(nodeDefCol)])
+          } else {
+            node = R.head(
+              await NodeRepository.fetchChildNodesByNodeDefUuids(surveyId, recordUuid, parentUuid, [nodeDefUuidCol])
+            )
+          }
```
Comment (minotogna) [inline server/modules/surveyRdb/manager/surveyRdbManager.js:133]: can we do just two fetches here? one from node table and one from resultNode table?

File: server/modules/surveyRdb/manager/surveyRdbManager.js [hunk 3]
```diff
@@ -100,22 +102,35 @@ export const queryTable = async (
       rows.map(async (row) => {
         const recordUuid = row[DataTable.colNameRecordUuuid]
         const record = await RecordRepository.fetchRecordByUuid(surveyId, recordUuid)
-        const parentNodeUuid = R.prop(`${NodeDef.getName(nodeDefTable)}_uuid`, row)
+        const parentNodeUuid = R.prop(RdbDataView.getColUuid(nodeDefTable), row)
```
Comment (minotogna) [inline server/modules/surveyRdb/manager/surveyRdbManager.js:105]: RdbDataView.getColUuid is deprecated. use ViewDataNodeDef

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js (hunk 1 above)
Comment (SteRiccio) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:49]: ok

File: server/modules/surveyRdb/manager/surveyRdbManager.js (hunk 2 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/manager/surveyRdbManager.js:133]: they are a bit different, one fetch is by node uuid, the other is by parent node uuid and node def uuids...

File: server/modules/surveyRdb/manager/surveyRdbManager.js (hunk 3 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/manager/surveyRdbManager.js:105]: ok

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js (hunk 1 above)
Comment (minotogna) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:49]: Since refactoring at the moment might take too long, and we don't want to use connect anymore, you can 
```canEditRecord={(...args) => dispatch(canEditRecord(...args))}```

Comment (SteRiccio) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:49]: ok, good

File: server/modules/record/repository/node/read.js [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+ * @param {!object} params - The query parameters.
+ * @param {!string} params.surveyId - The survey id.
+ * @param {string} [params.uuid=null] - The node uuid to filter by.
+ * @param {string} [params.recordUuid=null] - The record uuid to filter by.
+ * @param {string} [params.parentUuid=null] - The parent node uuid to filter by.
+ * @param {string} [params.nodeDefUuid=null] - The node definition uuid to filter by.
+ * @param {boolean} [params.draft=false] - Whether to fetch draft props or only published ones.
+ * @param {pgPromise.IDatabase} [client=db] - The database client.
+ *
+ * @returns {Promise<any[]>} - The result promise.
```
Comment (minotogna) [inline server/modules/record/repository/node/read.js:25]: better ```@returns {Promise<Node[]>} - The result promise.``` ?

File: common/model/db/tables/node/select.js [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+    LEFT OUTER JOIN
+        ${schemaSurvey}.taxon t
+    ON
+        (${this.columnValue}->>'${Node.valuePropKeys.taxonUuid}')::uuid = t.uuid
+    LEFT OUTER JOIN
+        ${schemaSurvey}.taxon_vernacular_name v
+    ON
+        (${this.columnValue}->>'${Node.valuePropKeys.vernacularNameUuid}')::uuid = v.uuid`
+
+  return `${query} WHERE ${whereConditions.join(' AND ')}`
```
Comment (minotogna) [inline common/model/db/tables/node/select.js:69]: Where conditions can be an empty array. use ```whereConditions.length > 0  ? : ```

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumn.js [hunk 6]
```diff
@@ -43,32 +51,48 @@ const TableColumn = props => {
...
+          })}
         </div>
       )}
     </div>
   )
 }
 
+TableColumn.propTypes = {
+  nodeDef: PropTypes.object.isRequired,
+  row: PropTypes.object,
```
Comment (minotogna) [inline webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumn.js:88]: isn't row required ?

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js [hunk 7]
```diff
@@ -1,77 +1,67 @@
...
+        surveyCycleKey={surveyCycleKey}
+        nodeDef={nodeDef}
+        parentNode={parentNode}
+        nodes={[node]}
+        entry
+        entryDataQuery
+        edit={false}
+        renderType={NodeDefLayout.renderType.tableBody}
+        canEditRecord={canEditRecord}
+        readOnly={NodeDef.isReadOnly(nodeDef) || NodeDef.isAnalysis(nodeDef)}
```
Comment (minotogna) [inline webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:45]: can readOnly be calculated inside NodeDefTableCellBody? it has the nodeDef

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js [hunk 8]
```diff
@@ -1,77 +1,67 @@
...
+
+    const parentNode = {
+      [Node.keys.recordUuid]: Record.getUuid(record),
+      [Node.keys.parentUuid]: parentUuid,
     }
 
-    return null
+    return (
+      <NodeDefTableCellBody
+        className="test"
```
Comment (minotogna) [inline webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:34]: test?

File: server/modules/surveyRdb/manager/surveyRdbManager.js [hunk 9]
```diff
@@ -52,6 +56,46 @@ const _getQueryData = async (survey, nodeDefUuidTable, nodeDefUuidCols = []) =>
   }
 }
 
+const _fetchColumnData = async (survey, nodeDefTable, row, nodeDefUuid) => {
+  const surveyId = Survey.getId(survey)
+  const nodeDef = Survey.getNodeDefByUuid(nodeDefUuid)(survey)
+  const nodeDefParent = Survey.getNodeDefParent(nodeDef)(survey)
+  const parentUuidColName = RdbDataView.getColUuid(nodeDefParent)
```
Comment (minotogna) [inline server/modules/surveyRdb/manager/surveyRdbManager.js:63]: Deprecated. use ```ColumnNodeDef.getColName```

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/dataQueryView.scss [hunk 10]
```diff
@@ -28,7 +27,11 @@ $rowHeaderHeight: 45px;
 
     .survey-form__node-def-table-cell-header {
       background-color: transparent;
-      grid-row-gap: .5rem;
+      grid-row-gap: 0.5rem;
+    }
+
+    .table__cell.readonly {
+      background-color: $greyBorder;
```
Comment (minotogna) [inline webapp/loggedin/modules/data/dataVis/dataQuery/components/dataQueryView.scss:34]: check the color in mockup and issue description

File: server/modules/record/repository/node/read.js (hunk 4 above)
Comment (SteRiccio) [reply server/modules/record/repository/node/read.js:25]: right

File: common/model/db/tables/node/select.js (hunk 5 above)
Comment (SteRiccio) [reply common/model/db/tables/node/select.js:69]: ok

File: common/model/db/tables/node/select.js [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+export function getSelect(params) {
+  const { uuid = null, recordUuid = null, parentUuid = null, nodeDefUuid = null, draft = false } = params
+
+  const _getPropsCombined = (table) => (draft ? `${table}.props || ${table}.props_draft` : `${table}.props`)
+
+  const propsTaxon = _getPropsCombined('t')
+  const propsVernacularName = _getPropsCombined('v')
+  const propsCategoryItem = _getPropsCombined('c')
+
+  const schemaSurvey = Schemata.getSchemaSurvey(this.surveyId)
```
Comment (minotogna) [inline common/model/db/tables/node/select.js:24]: can you use here this.schema?

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 12]
```diff
@@ -12,31 +12,133 @@ import * as Expression from '../../../../../core/expressionParser/expression'
...
+ * @param {!number} [params.limit] - The query limit.
+ * @param {!object} [params.filterExpr] - The filter expression object.
+ * @param {Array} [params.sort=[]] - The sort conditions.
+ * @param {boolean} [params.editMode=false] - Whether to fetch row ready to be edited (fetches nodes and records).
+ * @param {boolean} [params.queryStream=false] - Whether to fetch rows to be streamed.
+ * @param {pgPromise.IDatabase} client - The database client.
+ *
+ * @returns {Promise<object>} - An object with fetched rows and selected fields.
+ */
+export const runSelect = async (params, client = db) => {
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:101]: this should become fetchViewData. (merge the method below)

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 13]
```diff
@@ -12,31 +12,133 @@ import * as Expression from '../../../../../core/expressionParser/expression'
 
 import * as SchemaRdb from '../../../../../common/surveyRdb/schemaRdb'
 import * as NodeDefTable from '../../../../../common/surveyRdb/nodeDefTable'
-
 import * as DataSort from '../../../../../common/surveyRdb/dataSort'
 import * as DataFilter from '../../../../../common/surveyRdb/dataFilter'
-import { ViewDataNodeDef } from '../../../../../common/model/db'
+import { ViewDataNodeDef, TableNode, TableResultNode, ColumnNodeDef } from '../../../../../common/model/db'
 import { getSurveyDBSchema } from '../../../survey/repository/surveySchemaRepositoryUtils'
+import { dbTransformCallback as dbTransformCallbackNode } from '../../../record/repository/node'
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:19]: a repository cannot use another repository. add this method to tableNode

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 14]
```diff
@@ -12,31 +12,133 @@ import * as Expression from '../../../../../core/expressionParser/expression'
...
+/**
+ * Runs a select query on a data view associated to an entity node definition.
+ *
+ * @param {!object} params - The query parameters.
+ * @param {!Survey} [params.survey] - The survey.
+ * @param {!string} [params.nodeDefUuidTable] - The UUID of the node def associated to the view to select.
+ * @param {!Array} [params.nodeDefUuidCols] - The UUIDs of the node defs associated to the selected columns.
+ * @param {!number} [params.offset] - The query offset.
+ * @param {!number} [params.limit] - The query limit.
+ * @param {!object} [params.filterExpr] - The filter expression object.
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:93]: call this filter

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 15]
```diff
@@ -12,31 +12,133 @@ import * as Expression from '../../../../../core/expressionParser/expression'
...
+ * @param {Array} [params.sort=[]] - The sort conditions.
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:94]: add type Sort

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 16]
```diff
@@ -12,31 +12,133 @@ import * as Expression from '../../../../../core/expressionParser/expression'
...
+ * @param {boolean} [params.editMode=false] - Whether to fetch row ready to be edited (fetches nodes and records).
+ * @param {boolean} [params.queryStream=false] - Whether to fetch rows to be streamed.
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:96]: call this stream

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 17]
```diff
@@ -46,29 +148,36 @@ export const runSelect = async (
...
+    schema: viewDataNodeDef.schema,
+    tableName: viewDataNodeDef.name,
     limit,
     offset,
   }
 
-  return queryStream ? new dbUtils.QueryStream(dbUtils.formatQuery(select, params)) : client.any(select, params)
+  const result = queryStream
+    ? new dbUtils.QueryStream(dbUtils.formatQuery(select, queryParams))
+    : await client.map(select, queryParams, _dbTransformCallbackSelect(viewDataNodeDef, editMode, nodeDefCols))
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:174]: don't await here

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 18]
```diff
@@ -46,29 +148,36 @@ export const runSelect = async (
...
+
+  return {
+    result,
+    // Consider only user selected fields
+    selectFields: nodeDefCols.map((nodeDefCol) => new ColumnNodeDef(viewDataNodeDef, nodeDefCol).names).flat(),
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:179]: do you really need to return the selectFields?

File: server/modules/record/repository/node/read.js [hunk 19]
```diff
@@ -0,0 +1,31 @@
...
+import camelize from 'camelize'
+import * as R from 'ramda'
+
+import { TableNode } from '../../../../../common/model/db'
+import * as Node from '../../../../../core/record/node'
+
+import { db } from '../../../../db/db'
+
+export const dbTransformCallback = (node) =>
+  node ? R.pipe(R.dissoc(Node.keys.meta), camelize, R.assoc(Node.keys.meta, R.prop(Node.keys.meta, node)))(node) : null
```
Comment (minotogna) [inline server/modules/record/repository/node/read.js:11]: why a null node?

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 20]
```diff
@@ -12,31 +12,133 @@ import * as Expression from '../../../../../core/expressionParser/expression'
...
-) => {
-  const schemaName = SchemaRdb.getName(surveyId)
-  // Columns
-  const colParams = cols.reduce((params, col, i) => ({ ...params, [`col_${i}`]: col }), {})
-  const colParamNames = Object.keys(colParams).map((n) => `$/${n}:name/`)
+// TODO move it to ViewDataNodeDef ?
+const _getParentNodeUuidColName = (viewDataNodeDef, nodeDef) => {
+  const { survey } = viewDataNodeDef
+  const nodeDefParent = Survey.getNodeDefParent(nodeDef)(survey)
+  return R.head(new ColumnNodeDef(viewDataNodeDef, nodeDefParent).names)
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:28]: use static method ```ColumnNodeDef.getName(nodeDefParent)```

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 21]
```diff
@@ -12,31 +12,133 @@ import * as Expression from '../../../../../core/expressionParser/expression'
...
+        node: dbTransformCallbackNode(nodeJson),
+        parentUuid,
+      }
+      delete rowUpdated[nodeDefColUuid]
+    })
+    // Record column
+    rowUpdated.record = camelize(rowUpdated.record)
+    // Parent node uuid column
+    const nodeDefParentColumnUuid = _getParentNodeUuidColName(viewDataNodeDef, viewDataNodeDef.nodeDef)
+    rowUpdated.parentNodeUuid = rowUpdated[nodeDefParentColumnUuid]
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:79]: why parentNodeUuid custom name?

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumn.js (hunk 6 above)
Comment (SteRiccio) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumn.js:88]: no

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js (hunk 8 above)
Comment (SteRiccio) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:34]: ooopppsss I've forgot it!

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js (hunk 7 above)
Comment (SteRiccio) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:45]: yes... I didn't want to change even NodeDefTableCellBody...

Comment (minotogna) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:45]: but doest NodeDefTableBody needs readOnly prop?

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableRows.js [hunk 22]
```diff
@@ -1,35 +1,25 @@
...
   const i18n = useI18n()
+  const history = useHistory()
 
   return (
     <div className="table__content">
       <div className="table__rows">
         <div className="table__row-header">
           <div style={{ width: defaultColWidth }}>{i18n.t('dataView.rowNum')}</div>
-          <TableColumns nodeDefCols={nodeDefCols} lang={lang} colWidth={colWidth} editMode={editMode} />
+          <TableColumns nodeDefCols={nodeDefCols} colWidth={colWidth} editMode={editMode} />
```
[the remark this answers is not in the document]
Comment (SteRiccio) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableRows.js:22]: uhm, yes, we save a very simple component

File: common/model/db/tables/node/select.js (hunk 11 above)
Comment (SteRiccio) [reply common/model/db/tables/node/select.js:24]: the same file is used to generate the select for the result node table; in that case the schema is different.

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 12 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:101]: ok

File: common/model/db/tables/node/select.js (hunk 11 above)
Comment (minotogna) [reply common/model/db/tables/node/select.js:24]: then add the table object models needed. (category_item, etc..)

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 16 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:96]: ok

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 17 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:174]: ok

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 18 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:179]: uhm, no, we can calculate them in the manager

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 13 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:19]: ok

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 14 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:93]: ok

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 15 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:94]: ok

File: server/modules/record/repository/node/read.js (hunk 19 above)
Comment (SteRiccio) [reply server/modules/record/repository/node/read.js:11]: right

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 20 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:28]: ok

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 21 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:79]: it's used to easily get the parent node uuid when generating the record edit url

File: common/model/db/tables/node/select.js (hunk 11 above)
Comment (SteRiccio) [reply common/model/db/tables/node/select.js:24]: ok

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 21 above)
Comment (minotogna) [reply server/modules/surveyRdb/repository/dataView/read.js:142]: the question was, since we always use parentUuid, the custom name parentNodeUuid?

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 23]
```diff
@@ -12,63 +12,207 @@ import * as Expression from '../../../../../core/expressionParser/expression'
...
+      // selected node def columns
+      ...nodeDefCols.map((nodeDefCol) => `${viewDataNodeDef.alias}.${ColumnNodeDef.getColName(nodeDefCol)}`),
+    ]
+    // Add ancestor uuid columns
+    Survey.visitAncestorsAndSelf(nodeDef, (nodeDefAncestor) => {
+      if (!(NodeDef.isVirtual(nodeDefAncestor) || NodeDef.isRoot(nodeDefAncestor))) {
+        const columnUuid = `${viewDataNodeDef.alias}.${ColumnNodeDef.getColName(nodeDefAncestor)}`
+        selectFields.push(columnUuid)
+      }
+    })(survey)
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:60]: add a method to ViewDataNodeDef.columnUuids that get the appends the parent columns and so on..

File: common/model/db/tables/node/table.js [hunk 24]
```diff
@@ -0,0 +1,55 @@
...
+    return super.getColumn(columnSet.value)
+  }
+
+  get columnMeta() {
+    return super.getColumn(columnSet.meta)
+  }
+}
+
+TableNode.dbTransformCallback = (node) =>
+  node ? R.pipe(R.dissoc(Node.keys.meta), camelize, R.assoc(Node.keys.meta, R.prop(Node.keys.meta, node)))(node) : null
```
Comment (minotogna) [inline common/model/db/tables/node/table.js:53]: why node null??????

File: server/modules/surveyRdb/repository/dataView/read.js [hunk 25]
```diff
@@ -12,63 +12,207 @@ import * as Expression from '../../../../../core/expressionParser/expression'
...
+ */
+const _getFromClause = (params) => {
+  const { survey, nodeDef, editMode, nodeDefCols } = params
+  const viewDataNodeDef = new ViewDataNodeDef(survey, nodeDef)
+  const { surveyId } = viewDataNodeDef
+
+  const fromTables = [viewDataNodeDef.nameAliased]
+  if (editMode) {
+    fromTables.push(
+      ...[
```
Comment (minotogna) [inline server/modules/surveyRdb/repository/dataView/read.js:100]: do you need ...[...map ? would just ...map be enough ?

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 21 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:142]: aaa ok, it's clear now, I'll change it

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 23 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:60]: ok

File: common/model/db/tables/node/table.js (hunk 24 above)
Comment (SteRiccio) [reply common/model/db/tables/node/table.js:53]: right, it cannot happen, I'll change it

File: server/modules/surveyRdb/repository/dataView/read.js (hunk 25 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/repository/dataView/read.js:100]: right

File: webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js (hunk 7 above)
Comment (SteRiccio) [reply webapp/loggedin/modules/data/dataVis/dataQuery/components/tableColumnEdit.js:44]: that prop is passed to the NodeDef UI component together with all the props

File: common/model/db/tables/taxon/table.js [hunk 26]
```diff
@@ -0,0 +1,25 @@
...
+const columnSet = {
+  id: Table.columnSetCommon.id,
+  uuid: Table.columnSetCommon.uuid,
+  taxonomyUuid: 'taxonomy_uuid',
+  props: Table.columnSetCommon.props,
+  propsDraft: Table.columnSetCommon.propsDraft,
+}
+
+/**
+ * @typedef {module:arena.TableSurvey} module:arena.TableNode
```
Comment (minotogna) [inline common/model/db/tables/taxon/table.js:13]: copy & paste ;) this should be ```@typedef {module:arena.TableSurvey} module:arena.TableTaxon```

File: common/model/db/tables/categoryItem/table.js [hunk 27]
```diff
@@ -0,0 +1,30 @@
...
+  id: Table.columnSetCommon.id,
+  uuid: Table.columnSetCommon.uuid,
+  levelUuid: 'level_uuid',
+  parentUuid: 'parent_uuid',
+  props: Table.columnSetCommon.props,
+  propsDraft: Table.columnSetCommon.propsDraft,
+}
+
+/**
+ * @typedef {module:arena.TableSurvey} module:arena.TableNode
```
Comment (minotogna) [inline common/model/db/tables/categoryItem/table.js:14]: ```@typedef {module:arena.TableSurvey} module:arena.TableCategoryItem ```

File: common/model/db/tables/taxonVernacularName/table.js [hunk 28]
```diff
@@ -0,0 +1,25 @@
...
+const columnSet = {
+  id: Table.columnSetCommon.id,
+  uuid: Table.columnSetCommon.uuid,
+  taxonUuid: 'taxon_uuid',
+  props: Table.columnSetCommon.props,
+  propsDraft: Table.columnSetCommon.propsDraft,
+}
+
+/**
+ * @typedef {module:arena.TableSurvey} module:arena.TableNode
```
Comment (minotogna) [inline common/model/db/tables/taxonVernacularName/table.js:13]: ```@typedef {module:arena.TableSurvey} module:arena.TableTaxonVernacularName```

File: server/modules/surveyRdb/manager/surveyRdbManager.js [hunk 29]
```diff
@@ -55,81 +53,37 @@ const _getQueryData = async (survey, nodeDefUuidTable, nodeDefUuidCols = []) =>
...
-  nodeDefUuidCols = [],
+  nodeDef,
+  nodeDefCols = [],
   offset = 0,
   limit = null,
-  filterExpr = null,
+  filter = null,
   sort = [],
   editMode = false,
   streamOutput = null
```
Comment (minotogna) [inline server/modules/surveyRdb/manager/surveyRdbManager.js:63]: let's start using params here as well

File: server/modules/surveyRdb/manager/surveyRdbManager.js [hunk 30]
```diff
@@ -55,81 +53,37 @@ const _getQueryData = async (survey, nodeDefUuidTable, nodeDefUuidCols = []) =>
 export const queryTable = async (
```
Comment (minotogna) [inline server/modules/surveyRdb/manager/surveyRdbManager.js:53]: let's call this method fetchViewData

File: server/modules/surveyRdb/service/surveyRdbService.js [hunk 31]
```diff
@@ -6,7 +6,7 @@ import * as SurveyRdbManager from '@server/modules/surveyRdb/manager/surveyRdbMa
 const _fetchSurvey = async (surveyId, cycle) => {
   const surveyInfo = Survey.getSurveyInfo(await SurveyManager.fetchSurveyById(surveyId, true))
   const loadDraftDefs = Survey.isFromCollect(surveyInfo) && !Survey.isPublished(surveyInfo)
-  return await SurveyManager.fetchSurveyAndNodeDefsBySurveyId(surveyId, cycle, loadDraftDefs)
+  return SurveyManager.fetchSurveyAndNodeDefsBySurveyId(surveyId, cycle, loadDraftDefs)
 }
 
 export const queryTable = async (
```
Comment (minotogna) [inline server/modules/surveyRdb/service/surveyRdbService.js:12]: let's call this method fetchViewData

File: common/model/db/tables/taxon/table.js (hunk 26 above)
Comment (SteRiccio) [reply common/model/db/tables/taxon/table.js:13]: right!

File: common/model/db/tables/taxonVernacularName/table.js (hunk 28 above)
Comment (SteRiccio) [reply common/model/db/tables/taxonVernacularName/table.js:13]: yes

File: common/model/db/tables/categoryItem/table.js (hunk 27 above)
Comment (SteRiccio) [reply common/model/db/tables/categoryItem/table.js:14]: ok

File: server/modules/surveyRdb/manager/surveyRdbManager.js (hunk 29 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/manager/surveyRdbManager.js:63]: ok

File: server/modules/surveyRdb/manager/surveyRdbManager.js (hunk 30 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/manager/surveyRdbManager.js:53]: ok

File: server/modules/surveyRdb/service/surveyRdbService.js (hunk 31 above)
Comment (SteRiccio) [reply server/modules/surveyRdb/service/surveyRdbService.js:12]: ok
