### PR TITLE
Test/ui test

### LINKED ISSUE #815: LoginTest
- [x] Enter wrong email / password --> check error message appear
- [x] Enter right email / password --> check user is logged in and page displayed is home dashboard

### PR DESCRIPTION
**Pull request by sorja**
First test case for Taiko and Gauge setup
Contains:
- Login test
- Setup for Gauge and Taiko
Note:
- install:
  - mac os: brew install gauge
  - other: https://docs.gauge.org/getting_started/installing-gauge.html?os=macos&language=javascript&ide=null
- test/browser/node_modules is symlink
Resolves #815

### CODE REVIEW

File: test/browser/tests/step_implementation.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
+/* globals beforeSuite, afterSuite */
+const { $, waitFor, openBrowser, currentURL, closeBrowser, text } = require('taiko')
+const assert = require('assert')
```
Comment (minotogna) [inline test/browser/tests/step_implementation.js:3]: would it be possible to use chai instead of assert?

File: test/browser/.gitignore [hunk 2]
```diff
@@ -0,0 +1,8 @@
+# Gauge - metadata dir
```
Comment (minotogna) [inline test/browser/.gitignore:1]: why .gitignore here?

File: test/browser/env/default/default.properties [hunk 3]
```diff
@@ -0,0 +1,25 @@
+# default.properties
+# properties set here will be available to the test execution as environment variables
+
+# sample_key = sample_value
+
+#The path to the gauge reports directory. Should be either relative to the project directory or an absolute path
+gauge_reports_dir = reports
```
Comment (minotogna) [inline test/browser/env/default/default.properties:7]: can this be set as .gauge-reports ?

File: .eslintrc [hunk 4]
```diff
@@ -9,6 +9,9 @@
     "mocha": true,
     "node": true
   },
+  "globals": {
+    "step": "readonly"
+  },
```
Comment (sorja) [inline .eslintrc:14]: We can add globals here, helps avoid ex.
```
/* eslint-disable no-unused-expressions */
expect(await text(content).exists()).to.be.true
```

File: test/browser/tests/step_implementation.js [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+      : [],
+  })
+})
+
+afterSuite(async () => {
+  await closeBrowser()
+})
+
+step('Page contains <content>', async (content) => {
+  /* eslint-disable no-unused-expressions */
```
Comment (sorja) [inline test/browser/tests/step_implementation.js:29]: We can add globals to .eslintrc to avoid repetition

File: test/browser/tests/step_implementation.js (hunk 1 above)
Comment (SteRiccio) [reply test/browser/tests/step_implementation.js]: done

File: test/browser/env/default/default.properties (hunk 3 above)
Comment (sorja) [reply test/browser/env/default/default.properties:7]: i think better to have it without dot so it's not hidden (no reason to hide)

File: package.json [hunk 6]
```diff
@@ -16,6 +16,10 @@
     "create-migration": "./server/db/migration/create-migration.sh",
     "dev:server": "npm run build:server:dev && npm-run-all --parallel nodemon:prod watch:server",
     "nodemon:prod": "cross-env NODE_ENV=development node-dev --no-notify --inspect -- dist/server.js",
+    "test": "mochapack --timeout 30000 --display-error-details --webpack-config test/webpack.config.test.babel.js \"test/*/*.js\"",
+    "test:docker": "test/run_docker_tests.sh",
+    "test:browser": "gauge run -d test/browser/",
+    "preversion": "git diff --quiet || { echo \"Working directory is dirty\"; exit 1; }; yarn test:docker",
```
Comment (minotogna) [inline package.json:22]: preversion seems duplicate

File: .eslintrc (hunk 4 above)
Comment (minotogna) [reply .eslintrc:14]: I agree. there are many of those with expect. would it be possible to do so?

Comment (SteRiccio) [reply .eslintrc:14]: the problem is not with "expect", because the result of its invocation is used by the following function invocation; the problem is with ".true" or similar. There is a plugin we can use: https://www.npmjs.com/package/eslint-plugin-chai-friendly or maybe we can think about using something different than chai (maybe assert...?)

File: test/browser/specs/survey.md [hunk 7]
```diff
@@ -0,0 +1,24 @@
+# Survey specification
```
Comment (minotogna) [inline test/browser/specs/survey.md:1]: this is survey-create test. there will be more survey tests I imagine

File: test/browser/tests/survey.js [hunk 8]
```diff
@@ -0,0 +1,19 @@
+const { click, button, write, into, textBox, waitFor } = require('taiko')
+
+// TODO it should be improved: wait for the loader div to disappear
+const waitForLoadComplete = async () => {
```
Comment (minotogna) [inline test/browser/tests/survey.js:4]: this is a common utility function. extract it to some common place

File: .gitignore [hunk 9]
```diff
@@ -267,3 +267,6 @@ modules.xml
 .idea/sonarlint
 
 # End of https://www.gitignore.io/api/node,terraform,visualstudiocode,webstorm+all,macos,linux
+reports
+.gauge
+gauge-reports
```
Comment (minotogna) [inline .gitignore:272]: I don't like to idea to manually edit this generated .gitignore file. 
any better alternative?

File: test/browser/specs/survey.md (hunk 7 above)
Comment (SteRiccio) [reply test/browser/specs/survey.md:1]: sure, I'll reorganize them

File: test/browser/tests/survey.js (hunk 8 above)
Comment (SteRiccio) [reply test/browser/tests/survey.js:4]: right, I'll move it elsewhere

File: .gitignore (hunk 9 above)
Comment (SteRiccio) [reply .gitignore:272]: it should be modified from gitignore.io, but Gauge is not among the available options.
Extra exclusions can be put on top.

Comment (minotogna) [reply .gitignore:272]: but what is reports folder?
