### PR TITLE
Bug/node def default

### LINKED ISSUE #1405: DataEntry: NodeDefTaxon with default value doesn't allow updating value
Steps to reproduce:

1. create a nodeDefTaxon
2. Set a default value
3. goto form preview
4. delete code
5. The value gets updated with values from backend

Expected:
5. allow user to add new value or clear the default value

Test:
Test case is already in surveyFormPreview. uncomment it

### PR DESCRIPTION
**Pull request by ramirobg94**
## Related Issue

Resolves #1405 

## Brief description of the changes proposed and/or how the issue(s) has(have) been solved.

When someone is updating a node and in this updating, the user deletes the value, (the new value is empty), the default value is not going to be set.

In this case, seems that the user is trying to clean the value, maybe if she/he likes to recover the default value we should allow it in another way.

## How has this been tested
tests

##### Do you consider this PR needs further testing?
- [ ] No
- [x] Yes

## Types of changes

- [ ] Docs change 
- [ ] Refactoring 
- [ ] Dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Disclaimer

This affects other Nodes too, at the end is a common problem

### CODE REVIEW

File: server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js [hunk 1]
```diff
@@ -114,12 +114,16 @@ export const updateSelfAndDependentsDefaultValues = async (survey, record, node,
...
-
+      // 4. persist updated node value if changed and new value is not empty, and return updated node
       if (R.equals(oldValue, exprValue)) {
         return {}
       }
 
+      // if value is empty and node is Taxon leave empty, the user likes to clean the value
+      if (R.isEmpty(oldValue) && NodeDef.isTaxon(nodeDef)) {
+        return {}
+      }
```
Comment (minotogna) [inline server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js:125]: I just realised this happens to date, time, taxon, code, boolean, decimal, integer..
we should find a more consistent way to fix this 

Uploading Screen Recording 2021-03-03 at 05.42.32.mov…

**Review by minotogna — CHANGES_REQUESTED** [review]

File: server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js (hunk 1 above)
Comment (ramirobg94) [reply server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js:125]: I had the solution for that on the prev commit, but I reduced the scope only for the case of the bug, 

I will make changes to avoid default values on edit.

Comment (ramirobg94) [reply server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js:125]: the idea with this new line was add some prop to the NodeDEfs like cleanable 

If (R.isEmpty(oldValue) && NodeDef.isCleanable(nodeDef)) 

and allow overwriting with default values on value clean only if the NodeDef is not cleanable

Comment (minotogna) [reply server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js:125]: I think it's simply that the default value should not be applied on the node users are currently editing.
the concept of cleanable doesn't sound very robust

Comment (ramirobg94) [reply server/modules/record/manager/_recordManager/nodeUpdateDependentManager.js:125]: okey i will proceed in that way, avoid default on update

File: webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefBoolean.js [hunk 2]
```diff
@@ -26,7 +26,7 @@ const NodeDefBoolean = (props) => {
         className="btn btn-s btn-transparent flex-center"
         data-value={value}
         aria-disabled={disabled || !canEditRecord || readOnly}
-        onClick={() => updateNode(nodeDef, node, checked ? null : value)}
+        onClick={() => (checked ? null : updateNode(nodeDef, node, value))}
```
Comment (minotogna) [inline webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefBoolean.js:29]: does this prevent resetting a boolean node?

**Review by minotogna — CHANGES_REQUESTED** [review]
we should allow resetting Boolean value

File: webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefBoolean.js (hunk 2 above)
Comment (ramirobg94) [reply webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefBoolean.js]: I changed the test to avoid the reset

**Review by minotogna — APPROVED** [review]
