### PR TITLE
Fixed user edit bugs

### LINKED ISSUE #689: UserEdit bugs
Bug1 - User details not updated
- [x] Login as SystemAdmin --> go to UsersList --> click on one user (different from the logged in one) to go to user detail page --> Click on header profile picture --> click My Profile --> Name, emails, role remain the ones of previous user.

Bug 2 
- [x] Unable to move scale and rotate sliders

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #689

### CODE REVIEW

File: webapp/loggedin/modules/users/user/components/profilePictureEditor.js [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import './profilePictureEditor.scss'
 
+import * as PropTypes from 'prop-types'
+
 import * as FileTypes from '@webapp/utils/fileTypes'
 
 import React, { useEffect, useRef, useState } from 'react'
```
Comment (minotogna) [inline webapp/loggedin/modules/users/user/components/profilePictureEditor.js:7]: order should be as below and no need to import * from prop-types
```
import React, { useEffect, useRef, useState } from 'react'
import PropTypes from 'prop-types'

...rest
```

Comment (SteRiccio) [reply webapp/loggedin/modules/users/user/components/profilePictureEditor.js:7]: ok, right
