### PR TITLE
Fixed min/max count errors not shown in code attributes

### LINKED ISSUE #1134: Multiple code attribute: Minimum and Maximum required number, and Checkbox list
In the following example I have 2 multiple code attributes on the right side of UI, using the same categorical list:
image

in both cases there is property Mininum set to 0, and Maximum items to 2. This validation rule is not taken into account yet as an Error.

In addition, neither of input objects look good. Please add Checkbox list into the system, as follows:
image

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #1134 
The change that fixes the issue is only in the file webapp/components/survey/SurveyForm/nodeDefs/components/useValidation.js line 31.
The other changes have been done only to avoid ESLint errors.

### CODE REVIEW

File: core/record/_recordValidator/countValidator.js [hunk 1]
```diff
@@ -47,63 +55,50 @@ const _getNodePointers = (survey, record, nodes) => {
     if (NodeDef.isEntity(nodeDef) && !Node.isDeleted(node)) {
       // Add children node pointers
       const childDefs = Survey.getNodeDefChildren(nodeDef)(survey)
-
-      for (const childDef of childDefs) {
-        nodePointers.push({
+      nodePointers.push(
+        ...childDefs.map((childDef) => ({
```
Comment (ramirobg94) [inline core/record/_recordValidator/countValidator.js:59]: is it always an array?

**Review by ramirobg94 — APPROVED** [review]

File: core/record/_recordValidator/countValidator.js (hunk 1 above)
Comment (SteRiccio) [reply core/record/_recordValidator/countValidator.js:59]: childDefs is returned by Survey.getNodeDefChildren, and it's an array
