### PR TITLE
Fix/survey hierarchy virtual entity attributes

### LINKED ISSUE #720: SurveyHierarchy: Virtual entity doesn't show attributes
In Survey hierarchy, virtual entities doesn't show the attributes (see attachment)

- [x] It must list the source entity attributes + its own attributes

Screen Shot 2020-04-19 at 09 47 56

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #720

### CODE REVIEW

File: webapp/loggedin/surveyViews/nodeDefsSelector/components/attributesSelector.js [hunk 1]
```diff
@@ -1,83 +1,77 @@
...
-    isVisible && (
-      <button
-        className={`btn btn-s btn-node-def${isActive ? ' active' : ''}`}
-        onClick={() => onToggleAttribute(nodeDefUuid)}
-        disabled={!canSelectAttributes}
-      >
-        {NodeDef.getLabel(nodeDef, lang)}
-        {NodeDefUiProps.getIconByType(nodeDefType)}
-      </button>
+  const AttributeSelector = ({ nodeDef }) => {
```
Comment (minotogna) [inline webapp/loggedin/surveyViews/nodeDefsSelector/components/attributesSelector.js:35]: I just realized you moved AttributeSelector within AttributesSelector.
Move it to its own file

**Comment by minotogna** [comment]
Resolves #721

File: webapp/loggedin/surveyViews/nodeDefsSelector/components/attributesSelector.js (hunk 1 above)
Comment (SteRiccio) [reply webapp/loggedin/surveyViews/nodeDefsSelector/components/attributesSelector.js:35]: ok
