### PR TITLE
Relevant if expression: fixed expression evaluation using constant value

### LINKED ISSUE #1076: Relevant If: not working correctly in Preview
I have an text attribute (named as "cluster_accessibility_99") with condition that is filled within the previous field, but the text box remains grey:. The condition is 
cluster_accessibility == "99"

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #1076

### CODE REVIEW

File: webapp/components/expression/nodes/literal.js [hunk 1]
```diff
@@ -75,35 +90,38 @@ const Literal = (props) => {
...
             key: value,
-            label: i18n.t(`surveyForm.nodeDefBoolean.labelValue.${NodeDef.getLabelValue(nodeDefCurrent)}.${value}`),
+            label: i18n.t(`surveyForm.nodeDefBoolean.labelValue.${NodeDef.getLabelValue(nodeDef)}.${value}`),
           }))}
         />
       )
     }
-    return <input className="form-input" value={nodeValue} size={25} onChange={(e) => onChangeValue(e.target.value)} />
+    return (
+      <input className="form-input" value={nodeValueString} size={25} onChange={(e) => onChangeValue(e.target.value)} />
```
Comment (ramirobg94) [inline webapp/components/expression/nodes/literal.js:116]: change to event ahahahha ;)

**Review by ramirobg94 — APPROVED** [review]
