### PR TITLE
Fixed bug: NodeDefCode items not loaded in data entry 

### LINKED ISSUE #1042: NodeDefCode data entry: category items not loaded
Steps to reproduce the bug:
1. Add a new node definition of type Code
2. Add a new category with some items or use an existing (not empty) one
3. Open the data entry preview: items in the code node def are not visible (in both display modes)

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #1042

### CODE REVIEW

File: webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCodeCheckbox/Checkbox/Checkbox.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+import { useLang } from '@webapp/store/system'
+
+const Checkbox = (props) => {
+  const { edit, canEditRecord, item, readOnly, onItemAdd, onItemRemove, selectedItems } = props
+
+  const lang = useLang()
+
+  const selected = Boolean(selectedItems.find(CategoryItem.isEqual(item)))
+
+  return (
```
Comment (minotogna) [inline webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCodeCheckbox/Checkbox/Checkbox.js:15]: do we really need this component ?

Comment (SteRiccio) [reply webapp/components/survey/SurveyForm/nodeDefs/components/types/NodeDefCode/NodeDefCodeCheckbox/Checkbox/Checkbox.js:15]: actually no, I'll remove it
