### PR TITLE
Solved error creating record

### LINKED ISSUE #1203: Error creating new record
It happens in test environment with survey "SHARP+ 2020 (DEMO VERSION)".

When a new record is created, there is an error server side: 
```
[2020-10-30T00:41:26.281] [ERROR] arena - Thread - Error in thread:  BatchError {
    stat: { total: 101, succeeded: 18, failed: 83, duration: 92 }
    errors: [
        100: error: current transaction is aborted, commands ignored until end of transaction block
            at Parser.parseErrorMessage (/home/ste/dev/projects/openforis/arena/node_modules/pg-protocol/dist/parser.js:278:15)
            at Parser.handlePacket (/home/ste/dev/projects/openforis/arena/node_modules/pg-protocol/dist/parser.js:126:29)
            at Parser.parse (/home/ste/dev/projects/openforis/arena/node_modules/pg-protocol/dist/parser.js:39:38)
            at Socket.<anonymous> (/home/ste/dev/projects/openforis/arena/node_modules/pg-protocol/dist/index.js:8:42)
            at Socket.emit (events.js:315:20)
            at addChunk (_stream_readable.js:295:12)
            at readableAddChunk (_stream_readable.js:271:9)
            at Socket.Readable.push (_stream_readable.js:212:10)
            at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
        From previous event:
            at promise (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/promise-parser.js:30:20)
            at Task.$query (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/query.js:145:12)
            at Task.<anonymous> (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/query.js:263:23)
            at Task.query (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/task.js:117:34)
            at Object._update [as update] (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:16466:44)
            at /home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:16485:68
            at Array.map (<anonymous>)
            at Module.updateTable (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:16485:30)
            at _onNodesUpdate (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:14941:118)
            at async Task.<anonymous> (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:14890:7) {
          length: 144,
          severity: 'ERROR',
          code: '25P02',
          detail: undefined,
          hint: undefined,
          position: undefined,
          internalPosition: undefined,
          internalQuery: undefined,
          where: undefined,
          schema: undefined,
          table: undefined,
          column: undefined,
          dataType: undefined,
          constraint: undefined,
          file: 'postgres.c',
          line: '1105',
          routine: 'exec_simple_query'
        }
    ]
}
[2020-10-30T00:41:26.281] [ERROR] arena - Thread - BatchError {
    stat: { total: 101, succeeded: 18, failed: 83, duration: 92 }
    errors: [
        100: error: current transaction is aborted, commands ignored until end of transaction block
            at Parser.parseErrorMessage (/home/ste/dev/projects/openforis/arena/node_modules/pg-protocol/dist/parser.js:278:15)
            at Parser.handlePacket (/home/ste/dev/projects/openforis/arena/node_modules/pg-protocol/dist/parser.js:126:29)
            at Parser.parse (/home/ste/dev/projects/openforis/arena/node_modules/pg-protocol/dist/parser.js:39:38)
            at Socket.<anonymous> (/home/ste/dev/projects/openforis/arena/node_modules/pg-protocol/dist/index.js:8:42)
            at Socket.emit (events.js:315:20)
            at addChunk (_stream_readable.js:295:12)
            at readableAddChunk (_stream_readable.js:271:9)
            at Socket.Readable.push (_stream_readable.js:212:10)
            at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
        From previous event:
            at promise (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/promise-parser.js:30:20)
            at Task.$query (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/query.js:145:12)
            at Task.<anonymous> (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/query.js:263:23)
            at Task.query (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/task.js:117:34)
            at Object._update [as update] (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:16466:44)
            at /home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:16485:68
            at Array.map (<anonymous>)
            at Module.updateTable (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:16485:30)
            at _onNodesUpdate (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:14941:118)
            at async Task.<anonymous> (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:14890:7) {
          length: 144,
          severity: 'ERROR',
          code: '25P02',
          detail: undefined,
          hint: undefined,
          position: undefined,
          internalPosition: undefined,
          internalQuery: undefined,
          where: undefined,
          schema: undefined,
          table: undefined,
          column: undefined,
          dataType: undefined,
          constraint: undefined,
          file: 'postgres.c',
          line: '1105',
          routine: 'exec_simple_query'
        }
    ]
}
    at check (/home/ste/dev/projects/openforis/arena/node_modules/spex/lib/ext/batch.js:135:32)
    at step (/home/ste/dev/projects/openforis/arena/node_modules/spex/lib/ext/batch.js:109:17)
    at /home/ste/dev/projects/openforis/arena/node_modules/spex/lib/ext/batch.js:83:17
    at /home/ste/dev/projects/openforis/arena/node_modules/spex/lib/utils/index.js:62:25
    at AsyncResource.runInAsyncScope (async_hooks.js:186:9)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at promise (/home/ste/dev/projects/openforis/arena/node_modules/spex/lib/index.js:91:24)
    at Task.batch (/home/ste/dev/projects/openforis/arena/node_modules/spex/lib/ext/batch.js:73:12)
    at Task.<anonymous> (/home/ste/dev/projects/openforis/arena/node_modules/spex/lib/ext/batch.js:149:22)
    at Task.batch (/home/ste/dev/projects/openforis/arena/node_modules/pg-promise/lib/task.js:135:39)
    at Module.updateTable (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:16485:16)
    at _onNodesUpdate (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:14941:118)
    at async Task.<anonymous> (/home/ste/dev/projects/openforis/arena/dist/recordUpdateThread.js:14890:7)

```

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #1203

### CODE REVIEW

**Review by ramirobg94 — APPROVED** [review]

File: server/modules/surveyRdb/repository/dataTableUpdateRepository.js [hunk 1]
```diff
@@ -43,41 +45,42 @@ const _getColNames = (nodeDef, type) =>
...
-            colNames: _getColNames(nodeDef, type),
-            colValues: await _getColValues(survey, cycle, nodeDef, node, type),
-            rowUuid: _getRowUuid(nodeDef, node, nodes[Node.getParentUuid(node)]),
-          }
-        : null
-    }),
+const _toUpdates = (survey, cycle, nodeDefs, nodes) => {
+  // visit nodes with BFS algorithm to avoid FK constraints violations (sort nodes by hierarchy depth)
+  const nodesArray = Object.values(nodes).sort(
+    (nodeA, nodeB) => Node.getHierarchy(nodeA).length - Node.getHierarchy(nodeB).length
```
Comment (ramirobg94) [inline server/modules/surveyRdb/repository/dataTableUpdateRepository.js:66]: maybe you can extract this to sortByHierarchy
