### PR TITLE
Fixed validation of expressions using attributes inside single entities

### LINKED ISSUE #702: Expression editor: Allow usage of single entities attributes children of nodeDef context hierarchy
I imported a survey "1- BIOPHYSICAL SURVEY - CIRCULAR PLOT WITH MULTIPLE ENTITIES"
and in Collect Import Report there is line as follows:
Path: Cluster > Plots > Canopy Closure
Applicable if: plot_land_use/land_use='1'

In Expression Editor, there is no Land Use shown.

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #702

### CODE REVIEW

File: core/survey/_surveyValidator/nodeDefExpressionsValidator.js [hunk 1]
```diff
@@ -116,7 +134,7 @@ const _validateNodeDefExpr = async (survey, nodeDef, dependencyType, expr) => {
 
 const _validateExpressionProp = (survey, nodeDef, dependencyType) => async (propName, item) => {
```
Comment (ramirobg94) [inline core/survey/_surveyValidator/nodeDefExpressionsValidator.js:135]: is this async needed?

Comment (SteRiccio) [reply core/survey/_surveyValidator/nodeDefExpressionsValidator.js:135]: yes because it call _validateNodeDefExpr that is async!

**Review by ramirobg94 — APPROVED** [review]
