### PR TITLE
Paginator: replace current entry in history stack when changing page

### LINKED ISSUE #1059: Taxonomy editor: DONE button scrolls list backwards
When in a multipage taxonomic list user goes to page 2 or forwards, DONE button scrolls back the previous page and does not return the view of all taxonomic lists as it should do.
It is working wrong now.

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #1059

### CODE REVIEW

File: webapp/components/Table/Header/Header.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ const Header = (props) => {
           offset={offset}
           limit={limit}
           count={count}
-          setOffset={(offsetUpdated) => history.push(getLink(offsetUpdated))}
+          setOffset={(offsetUpdated) => history.replace(getLink(offsetUpdated))}
```
Comment (minotogna) [inline webapp/components/Table/Header/Header.js:24]: what if you are in survey list and go back?

**Review by minotogna — APPROVED** [review]
