### PR TITLE
Bug/users export

### LINKED ISSUE #1420: SurveyExport: Users include only users.json
Survey export include users.json and one json file per user.
However users.json already includes all user information.
Do not include a json file per user

### PR DESCRIPTION
**Pull request by ramirobg94**
## Related Issue

Resolves #1420 

## Brief description of the changes proposed an/or how the issue(s) has(have) been solved.

remove the files for each user

## How has this been tested

exporting and importing 

##### Do you consider this PR needs further testing?
- [ ] No
- [x] Yes

## Types of changes

- [ ] Docs change 
- [ ] Refactoring 
- [ ] Dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

File: server/modules/arenaImport/service/arenaImport/model/arenaSurveyFileZip.js [hunk 1]
```diff
@@ -69,9 +69,8 @@ export const getUsers = async (streamZipFile) => {
   return JSON.parse(users)
 }
 export const getUser = async (streamZipFile, uuid) => {
-  const userPath = getPathByUuid(uuid)(getPaths(streamZipFile))
-  const user = await streamZipFile.getEntryData(userPath)
-  return JSON.parse(user)
+  const users = await getUsers(streamZipFile)
+  return (users || []).find((user) => user.uuid === uuid)
```
Comment (minotogna) [inline server/modules/arenaImport/service/arenaImport/model/arenaSurveyFileZip.js:73]: this method can be remove because in 
_server/modules/arenaImport/service/arenaImport/metaImportJobs/usersImportJob.js_
you already have the list of users at line 86, so lines 88-90 can be removed as well

**Review by minotogna — CHANGES_REQUESTED** [review]

File: server/modules/arenaImport/service/arenaImport/model/arenaSurveyFileZip.js (hunk 1 above)
Comment (ramirobg94) [reply server/modules/arenaImport/service/arenaImport/model/arenaSurveyFileZip.js]: Changed

**Review by minotogna — APPROVED** [review]
