### PR TITLE
Fixed DataView edit mode - validation report not in sync

### LINKED ISSUE #766: DataView edit mode: validation report not in sync
When editing data from DataVis, row validation is not in sync with real validation status.

See video for details

[Screen Recording 2020-05-06 at 17.34.32.mov.zip](https://github.com/openforis/arena/files/4587747/Screen.Recording.2020-05-06.at.17.34.32.mov.zip)

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #766

### CODE REVIEW

File: webapp/commonComponents/hooks/useAuth.js [hunk 1]
```diff
@@ -12,3 +12,9 @@ export const useAuthCanEditRecord = (record) => {
   const user = useUser()
   return Authorizer.canEditRecord(user, record)
 }
+
+export const useAuthCanCleanseRecords = () => {
```
Comment (minotogna) [inline webapp/commonComponents/hooks/useAuth.js:16]: should we use singular here as useAuthCanEditRecord?
