### PR TITLE
Fixed Explorer date/time column format

### LINKED ISSUE #1172: Explorer: Date and Time format
A date field is shown in Explorer in a wrong format: 
image

Similarly, in Time we do not need to show seconds:
image

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #1172

### CODE REVIEW

File: webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js [hunk 1]
```diff
@@ -5,20 +5,28 @@ import * as A from '@core/arena'
...
-  if (NodeDef.isDecimal(nodeDef)) return NumberUtils.formatDecimal(value)
-  if (NodeDef.isBoolean(nodeDef))
-    return A.isNull(value)
-      ? ''
-      : i18n.t(`surveyForm.nodeDefBoolean.labelValue.${NodeDef.getLabelValue(nodeDef)}.${value}`)
-  return value
+  if (A.isNull(value)) {
+    return ''
+  }
+  const formatter = formatters[NodeDef.getType(nodeDef)]
```
Comment (ramirobg94) [inline webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js:28]: nice this strategy pattern here! 👍

**Review by ramirobg94 — APPROVED** [review]

File: webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js (hunk 1 above)
Comment (SteRiccio) [reply webapp/components/DataQuery/Visualizer/Table/Row/Column/ColumnData.js:28]: thanks!!! :)
