### PR TITLE
Fixed recent activities loading

### LINKED ISSUE #643: Recent Activity not fully loaded and buggy
- [x] In Home -> Recent Activity, the full logs is not loading.
- [x] There's a javascript error (see on test instance survey_1)

### PR DESCRIPTION
**Pull request by SteRiccio**
Fixes #643

### CODE REVIEW

File: webapp/loggedin/modules/home/dashboard/activityLog/actions.js [hunk 1]
```diff
@@ -14,43 +14,37 @@ import * as ActivityLogMessageParser from './activityLogMessageParser'
...
 export const homeActivityMessagesReset = 'home/activityLog/messages/reset'
 
-const fetchActivityLogs = async (state, offset = 0, limit = 30) => {
-  try {
-    const activityLogMessagesState = ActivityLogState.getMessages(state)
-    const survey = SurveyState.getSurvey(state)
-    const surveyId = Survey.getId(survey)
-    const i18n = AppState.getI18n(state)
+const fetchActivityLogs = async (state, newest = true) => {
+  const activityLogMessagesState = ActivityLogState.getMessages(state)
```
Comment (minotogna) [inline webapp/loggedin/modules/home/dashboard/activityLog/actions.js:18]: call this messages

Comment (SteRiccio) [reply webapp/loggedin/modules/home/dashboard/activityLog/actions.js:18]: ok
